module({},function(f){function u(a,c){return function(b){var d=Array.prototype.slice.call(arguments,1);null!==b?a(b):c.apply(null,d)}}f=function(a){return IMVU.BaseClass.extend("ImqConnectionStrategy",{connect:function(a){throw Error("ImqConnectionStrategy connect() function must be overridden");},encode:function(a){throw Error("ImqConnectionStrategy encode() function must be overridden");},decode:function(a){throw Error("ImqConnectionStrategy decode() function must be overridden");}})}({});var n=
function(a){a=IMVU.BaseClass.extend("ImqStream",{CONNECTING:0,OPEN:1,CLOSING:2,CLOSED:3,intialize:function(){this.state=null},send:function(a){throw Error("ImqStream send method must be overridden");},close:function(){throw Error("ImqStream close method must be overridden");}});_.extend(a.prototype,Backbone.Events);return a}({}),v=function(a){return a.ImqStream.extend("ImqWebSocketStream",{initialize:function(a){this.socket=a;this.state=this.CONNECTING;this._openCallback=this._onOpen.bind(this);this._messageCallback=
this._onMessage.bind(this);this._errorCallback=this._onError.bind(this);this._closeCallback=this._onClose.bind(this);this._addListeners()},send:function(a){this.socket.send(a)},close:function(){if(this.state===this.CONNECTING||this.state===this.OPEN)this.state=this.CLOSING,this.socket.close()},_addListeners:function(){this.socket.addEventListener("open",this._openCallback);this.socket.addEventListener("message",this._messageCallback);this.socket.addEventListener("error",this._errorCallback);this.socket.addEventListener("close",
this._closeCallback)},_removeListeners:function(){this.socket.removeEventListener("open",this._openCallback);this.socket.removeEventListener("message",this._messageCallback);this.socket.removeEventListener("error",this._errorCallback);this.socket.removeEventListener("close",this._closeCallback);this.socket=null},_onOpen:function(a){this.state=this.OPEN;this.trigger("open",a)},_onMessage:function(a){this.trigger("message",a)},_onError:function(a){this.trigger("error",a)},_onClose:function(a){this.state=
this.CLOSED;this._removeListeners();this.trigger("close",a)}})}({ImqStream:n}),r=function(a){function c(){Error.apply(this,arguments)}function b(a){var b=k[a.record];if("undefined"===typeof b)throw new c('Unable to parse "'+a.record+'" incoming message');return{type:a.record,data:b(a)}}var d=function(a){return window.btoa(window.unescape(window.encodeURIComponent(a)))},h=function(a){return window.decodeURIComponent(window.escape(window.atob(a)))},e,k;c.prototype=Error();e={msg_c2g_send_message:function(a){return{record:"msg_c2g_send_message",
queue:a.queueName,mount:a.mountName,message:d(a.message)}},msg_c2g_state_change:function(a){return{record:"msg_c2g_state_change",queue:a.queueName,mount:a.mountName,properties:e.state_property(a.delta)}},state_property:function(a){return _(a).reduce(function(a,c,b){a.push({record:"state_property",key:b,value:d(c)});return a},[])},msg_c2g_unsubscribe:function(a){return{record:"msg_c2g_unsubscribe",queues:a}},msg_c2g_subscribe:function(a){return{record:"msg_c2g_subscribe",queues:a}},msg_c2g_connect:function(a){return{record:"msg_c2g_connect",
user_id:a.user_id,cookie:d(a.cookie),metadata:_.map(a.metadata,function(a,c){return{record:"metadata",key:c,value:d(a)}})}},msg_c2g_open_floodgates:function(a){return{record:"msg_c2g_open_floodgates"}},msg_c2g_ping:function(a){return{record:"msg_c2g_ping"}}};k={msg_g2c_result:function(a){return{opId:a.op_id,error:0===a.status?null:a.error_message}},msg_g2c_joined_queue:function(a){return{queueName:a.queue,userId:a.user_id}},msg_g2c_left_queue:function(a){return{queueName:a.queue,userId:a.user_id}},
msg_g2c_create_mount:function(a){var b={1:"message",2:"state"}[a.type],d={};if("undefined"===typeof b)throw new c("Mount created of unknown type: "+a.type);d.type=b;d.queueName=a.queue;d.mountName=a.mount;"state"===b&&(d.state=k._property_list(a.properties));return d},_property_list:function(a){return _(a).reduce(function(a,c){var d=b(c);a[d.data.key]=d.data.value;return a},{})},state_property:function(a){return{key:a.key,value:h(a.value)}},msg_g2c_send_message:function(a){return{queueName:a.queue,
mountName:a.mount,userId:h(a.user_id),message:h(a.message)}},msg_g2c_state_change:function(a){return{queueName:a.queue,mountName:a.mount,userId:a.user_id,delta:k._property_list(a.properties)}},msg_g2c_pong:function(a){return{}}};return{utf8_to_b64:d,b64_to_utf8:h,encode:function(a,b){var d=e[a];if("undefined"===typeof d)throw new c('Unable to parse "'+a+'" outgoing message');return JSON.stringify([d(b)])},decode:function(a){return b(JSON.parse(a))},ImqMessageUnknown:c}}({}),s=function(a){var c=a.ImqWebSocketStream,
b=a.ImqTranscoder;return a.ImqConnectionStrategy.extend("ImqWebSocketConnectionStrategy",{initialize:function(a){this.connectionFactory=a.socketFactory||window.WebSocket;this.URL=a.url},connect:function(){var a=new this.connectionFactory(this.URL);return new c(a)},encode:function(a,c){return b.encode(a,c)},decode:function(a){return b.decode(a)}})}({ImqConnectionStrategy:f,ImqWebSocketStream:v,ImqTranscoder:r}),n=function(a){return a.ImqStream.extend("ImqHttpStream",{dependencies:["XMLHttpRequest",
"timer"],initialize:function(a){this._config=a;this._timer=this._config.timer;this.XMLHttpRequest=this._config.serviceProvider.get("XMLHttpRequest");this.URL=this._config.httpUrl;this._connectionId=a.connectionId;this._retryDelay=a.networkErrorRetryDelay||2E3;this._maxRetries=a.maxNetworkErrorRetries||5;this._debug=a.debug||!1;this._sendSeq=1;this._ackSeq=this._requestSeq=0;this._requestQueue=[];this._receiveBuffer={};this._requestCount=0;this._openTimerHandle=this._config.timer.setTimeout(function(){this._log("connecting to",
this.URL);this._openTimerHandle=null;this.trigger("open",{})}.bind(this),1)},send:function(a){this._requestSeq++;var b=this._requestSeq,d=this._makeFrame([a],b),b={seq:b,data:a,xhr:null,retry:null,url:null};this._requestQueue.push(b);this._log("send message",a);this._sendRequest(d,b)},close:function(){this._log("closing stream");null!==this._openTimerHandle?(this._config.timer.clearTimeout(this._openTimerHandle),this._openTimerHandle=null):this._close()},_makeFrame:function(a,b){return{record:"http_framing",
session_id:this._connectionId,seq:b,ack:this._ackSeq,data:_.map(a,function(a){return{record:"framing",type:0,data:a}})}},_sendRequest:function(a,b){var d=0,h=function(){this._requestCount--;b.xhr.onload=null;b.xhr.onerror=null;200===b.xhr.status?(this._log(b.url,"<--",b.xhr.responseText),this._handleResponse(b.xhr.responseText,b)):(this._log("error response from server, closing connection:",b.xhr.status),this._close())}.bind(this),e=function(e){this._requestCount--;b.xhr.onload=null;b.xhr.onerror=
null;this._log("network error sending frame",a,e);d<this._maxRetries?(this._log("retrying in",this._retryDelay/1E3,"seconds"),d++,b.xhr=null,b.retry=this._timer.setTimeout(function(){b.retry=null;(0===this._requestCount||0<a.data.length)&&k()}.bind(this),this._retryDelay)):(this._log("maximum retries reached (",this._maxRetries,"), closing connection"),this._close())}.bind(this),k=function(){this._requestCount++;var d=this._makeRequestURL();b.url=d;this._log(b.url,"--\x3e",a);b.xhr=new this.XMLHttpRequest;
b.xhr.open("POST",d,!0);b.xhr.setRequestHeader("Accept","application/octet-stream");b.xhr.setRequestHeader("Content-Type","application/octet-stream");b.xhr.onload=h;b.xhr.onerror=e;b.xhr.timeout=6E4;b.xhr.send(JSON.stringify(a))}.bind(this);k()},_makeRequestURL:function(){var a=this.URL+"?seq="+this._sendSeq;this._sendSeq++;return a},_handleResponse:function(a,b){var d=null;try{d=JSON.parse(a)}catch(h){this._log("error decoding response json, closing connection:",h);this._close();return}if(this._validateFrame(d)){for(;0<
this._requestQueue.length;){var e=this._requestQueue[0];if(e.seq>d.ack)break;this._log("removing sequence",e.seq,"from send queue");this._requestQueue.shift()}var k=[];if(0<d.seq){for(var e=d.seq-d.data.length+1,g=0;g<d.data.length;g++){var f=d.data[g];this._log("received message sequence",e,":",f.data);if("msg_g2c_connection_closed"===f.data.record){this._log("aborting connecting due to msg_g2c_connection_closed message");this._close();return}"undefined"===typeof this._receiveBuffer[e]&&e>this._ackSeq&&
(this._receiveBuffer[e]=f.data);e++}d=_.range(this._ackSeq+1,d.seq+1);for(g=0;g<d.length;g++){e=d[g];if("undefined"===typeof this._receiveBuffer[e]){this._log("sequence",e,"is missing, not delivering or acking messages beyond sequence",this._ackSeq);break}this._ackSeq=e;k.push(this._receiveBuffer[e]);delete this._receiveBuffer[e]}}d=0;f=[];for(g=0;g<this._requestQueue.length;g++){e=this._requestQueue[g];if(e.seq>b.seq)break;this._log("sequence",e.seq,"was not acknowledged, resending");f.push(e.data);
d=e.seq}0<f.length&&(g=this._makeFrame(f,d),this._sendRequest(g,b));_.each(k,function(a){this.trigger("message",{data:a})}.bind(this));0===this._requestCount&&(this._log("no outstanding requests, initiating poll request"),this._sendRequest(this._makeFrame([],0),b))}else this._log("invalid frame received, closing connection:",d),this._close()},_validateFrame:function(a){return"object"===typeof a&&"http_framing"===a.record&&"number"===typeof a.seq&&"number"===typeof a.ack&&"object"===typeof a.data&&
Array.isArray(a.data)&&_.reduce(a.data,function(a,d){return a&&"object"===typeof d&&"framing"===d.record&&"object"===typeof d.data},!0)},_close:function(){_.each(this._requestQueue,function(a){null!==a.xhr&&a.xhr.abort();null!==a.retry&&this._timer.clearTimeout(a.retry)}.bind(this));this.trigger("close",{})},_log:function(){if(this._debug){var a=[(new Date).toLocaleString()];_.each(arguments,function(b){a.push(b)});console.log.apply(console,a)}}})}({ImqStream:n}),w=function(a){var c=a.ImqHttpStream,
b=a.ImqTranscoder;return a.ImqConnectionStrategy.extend("ImqHttpConnectionStrategy",{initialize:function(a){this.config=a;this.URL=a.httpUrl},connect:function(){var a=[];if("undefined"!==typeof window.crypto)a=new Uint8Array(32),window.crypto.getRandomValues(a),a=_.map(a,function(a){return a&15});else for(var b=0;32>b;b++)a.push(Math.floor(16*Math.random()));this.config.connectionId=this.config.sessionId+_.reduce(a,function(a,b){return a+(9<b?String.fromCharCode(97+(b-10)):String.fromCharCode(48+
b))},"");return new c(this.config)},encode:function(a,c){var e=b.encode(a,c);return JSON.parse(e)[0]},decode:function(a){a=JSON.stringify(a);return b.decode(a)}})}({ImqConnectionStrategy:f,ImqHttpStream:n,ImqTranscoder:r}),m=function(a){var c=[5E3,15E3,45E3,9E4,18E4];a=IMVU.BaseClass.extend("ImqConnection",{dependencies:["timer"],CLOSED:0,CONNECTING:1,AUTHENTICATING:2,AUTHENTICATED:3,WAITING:4,initialize:function(a){this._setState(this.CLOSED);this._config=a;this._config.onPreReconnectCallback=this._config.onPreReconnectCallback||
function(a){a(null,null)};this._config.pingInterval=this._config.pingInterval||15E3;this._config.reconnect=this._config.reconnect||c;this._config.serverTimeoutInterval=this._config.serverTimeoutInterval||6E4;this._currentStrategy=this._stream=null;this._connectRetryIntervalIndex=this._currentStrategyIndex=0;this._lastMessageTime=this._receivedMessageTimerHandle=this._pingTimerHandler=this._connectRetryTimerHandle=null},connect:function(){if(this.state===this.WAITING||this.state===this.CLOSED)this._clearConnectRetryTimer(),
this._setState(this.CONNECTING),this._currentStrategyIndex>=this._config.strategies.length&&(this._currentStrategyIndex=0),this._currentStrategy=this._config.strategies[this._currentStrategyIndex],this._currentStrategyIndex++,console.log("Connecting to IMQ via '"+this._currentStrategy.URL+"' as user '"+this._config.userId+"'"),this._stream=this._currentStrategy.connect(),this._stream.on("open",function(a){this._onOpen(a)}.bind(this)),this._stream.on("message",this._onMessage,this),this._stream.on("error",
this._onError,this),this._stream.on("close",this._onClose,this),this._scheduleServerTimeout()},send:function(a,c){this._send(a,c)},close:function(){console.log("Disconnecting from IMQ");this._reset();this._disconnect();this._setState(this.CLOSED)},_setState:function(a,c){this.state=a;a===this.WAITING?this.trigger("state",a,this._config.timer.getTime()+c):this.trigger("state",a)},_onOpen:function(a){this._setState(this.AUTHENTICATING);this._stream.send(this._currentStrategy.encode("msg_c2g_connect",
{user_id:this._config.userId,cookie:this._config.sessionId,metadata:this._config.metadata}))},_onMessage:function(a){this._scheduleServerTimeout();this._lastMessageTime=this._config.timer.getTime();a=this._currentStrategy.decode(a.data);this.state===this.AUTHENTICATING?("msg_g2c_result"===a.type?null===a.data.error?(console.log("IMQ authenticated"),this._sendOpenFloodgates(),this._onAuthenticated()):console.log("Failed to authenticate with IMQ: "+a.data.error):console.log("unexpected message type during IMQ authentication: "+
a.type),this.state!==this.AUTHENTICATED&&this._onDisconnected()):"msg_g2c_pong"!==a.type&&this.trigger("message",a)},_onError:function(a){console.log("IMQ WebSocket error!")},_onClose:function(){this._onDisconnected()},_onDisconnected:function(){this._disconnect();console.log("Connection to IMQ closed");this._reconnect()},_onAuthenticated:function(){this._setState(this.AUTHENTICATED);this._reset()},_reset:function(){this._currentStrategyIndex=this._connectRetryIntervalIndex=0},_disconnect:function(){this._clearConnectRetryTimer();
this._clearPingTimer();this._clearServerTimer();null!==this._stream&&(this._stream.off(),this._stream.close(),this._stream=null)},_clearConnectRetryTimer:function(){null!==this._connectRetryTimerHandle&&(this._config.timer.clearTimeout(this._connectRetryTimerHandle),this._connectRetryTimerHandle=null)},_reconnect:function(){if(this._currentStrategyIndex<this._config.strategies.length)this.state=this.WAITING,this.connect();else{this._connectRetryIntervalIndex===this._config.reconnect.length&&(this._connectRetryIntervalIndex=
0);var a=this._config.reconnect[this._connectRetryIntervalIndex];console.log("Reconnecting to IMQ in "+a/1E3+" seconds");this._setState(this.WAITING,a);this._connectRetryTimerHandle=this._config.timer.setTimeout(function(){this._config.onPreReconnectCallback(function(a,b){null!==a?(console.log("Error in IMQ pre-reconnect callback: "+a),this._reconnect()):(_.extend(this._config,b),this._currentStrategyIndex=0,this.connect())}.bind(this),this._config.timer.getTime()-this._lastMessageTime)}.bind(this),
a);this._connectRetryIntervalIndex++}},_sendOpenFloodgates:function(){this._send("msg_c2g_open_floodgates",{})},_send:function(a,c){this._schedulePing();this._stream.send(this._currentStrategy.encode(a,c))},_scheduleServerTimeout:function(){this._clearServerTimer();this._receivedMessageTimerHandle=this._config.timer.setTimeout(this._onServerTimeout.bind(this),this._config.serverTimeoutInterval)},_clearServerTimer:function(){null!==this._receivedMessageTimerHandle&&(this._config.timer.clearTimeout(this._receivedMessageTimerHandle),
this._receivedMessageTimerHandle=null)},_onServerTimeout:function(){console.log("No message from IMQ server for "+this._config.serverTimeoutInterval/1E3+" seconds, disconnecting");this._onDisconnected()},_schedulePing:function(){this._clearPingTimer();this._pingTimerHandle=this._config.timer.setTimeout(this._sendPing.bind(this),this._config.pingInterval)},_clearPingTimer:function(){null!==this._pingTimerHandle&&(this._config.timer.clearTimeout(this._pingTimerHandle),this._pingTimerHandle=null)},_sendPing:function(){this._send("msg_c2g_ping",
{})}});_.extend(a.prototype,Backbone.Events);return a}({}),l={};l[m.prototype.CLOSED]="disconnected";l[m.prototype.CONNECTING]="connecting";l[m.prototype.AUTHENTICATING]="authenticating";l[m.prototype.AUTHENTICATED]="connected";l[m.prototype.WAITING]="disconnected";f=function(a,c){this.trigger("subscriberUpdate",{user_id:a.userId,action:a.action,queue:this.queue.name,mount:this.name,subscribers:c})};var p=IMVU.BaseClass.extend("ImqMessageMount",{initialize:function(a,c){this.queue=a;this.name=c},
handleMessage:function(a){this.trigger("message",{user_id:a.userId,queue:this.queue.name,mount:this.name,message:a.message})},handleSubscriberUpdate:f,sendMessage:function(a,c){this.queue.sendMessage(this.name,a,c)},unsubscribe:function(){this.queue.unsubscribe(this.name)},getSubscribers:function(){return this.queue.subscribers}});_.extend(p.prototype,Backbone.Events);var q=IMVU.BaseClass.extend("ImqStateMount",{initialize:function(a,c){this.queue=a;this.name=c;this.state={}},__applyDelta:function(a,
c){return _(c).reduce(function(a,d,h){""===c[h]?delete a[h]:a[h]=d;return a},a)},reset:function(a){this.state=a;this.trigger("stateChange",{queue:this.queue.name,mount:this.name,state:this.state})},handleStateChange:function(a){this.state=this.__applyDelta(this.state,a.delta);this.trigger("stateChange",{user_id:a.userId,queue:this.queue.name,mount:this.name,delta:a.delta,state:this.state})},handleSubscriberUpdate:f,sendStateChange:function(a,c){this.queue.sendStateChange(this.name,a,c)},unsubscribe:function(){this.queue.unsubscribe(this.name)},
getSubscribers:function(){return this.queue.subscribers}});_.extend(q.prototype,Backbone.Events);var x=IMVU.BaseClass.extend("ImqQueue",{initialize:function(a,c){this.name=c;this.manager=a;this.messageMounts={};this.stateMounts={};this.subscribers={}},initMessageMount:function(a){this._getOrCreateMessageMount(a)},initStateMount:function(a,c){this._getOrCreateStateMount(a).reset(c)},_getOrCreateMessageMount:function(a){"undefined"===typeof this.messageMounts[a]&&(this.messageMounts[a]=new p(this,a));
return this.messageMounts[a]},_getOrCreateStateMount:function(a){"undefined"===typeof this.stateMounts[a]&&(this.stateMounts[a]=new q(this,a));return this.stateMounts[a]},getMessageMount:function(a){return this._getOrCreateMessageMount(a)},getStateMount:function(a){return this._getOrCreateStateMount(a)},dispatchSubscriberUpdate:function(a){function c(c){c.handleSubscriberUpdate(a,b)}"joined"===a.action?this.subscribers[a.userId]=!0:"left"===a.action&&delete this.subscribers[a.userId];var b=this.subscribers;
_.each(this.messageMounts,c);_.each(this.stateMounts,c)},dispatchMessage:function(a,c){this.getMessageMount(a).handleMessage(c)},dispatchState:function(a,c){this.getStateMount(a).handleStateChange(c)},sendMessage:function(a,c,b){this.manager.sendMessage(this.name,a,c,b)},sendStateChange:function(a,c,b){this.manager.sendStateChange(this.name,a,c,b)},unsubscribe:function(a){"undefined"!==typeof this.messageMounts[a]&&(this.messageMounts[a].off(),delete this.messageMounts[a]);"undefined"!==typeof this.stateMounts[a]&&
(this.stateMounts[a].off(),delete this.stateMounts[a]);0===Object.keys(this.stateMounts).length&&0===Object.keys(this.messageMounts).length&&this.manager._unsubscribeQueue(this.name,function(a){if(a)throw Error("Oh snap! "+a);})}});f=IMVU.BaseClass.extend("ImqManager",{dependencies:["Promise","timer"],initialize:function(a){this.config=a;this.Promise=a.Promise;this.timer=a.timer;this.queues={};this.__queuedSubscriptions=[];this.state=new Backbone.Model({status:"disconnected",connectAt:this.timer.getTime()});
var c=[];(a.socketFactory||window.WebSocket)&&c.push(new s(this.config));"undefined"!==typeof this.config.httpUrl&&c.push(new w(this.config));0===c.length&&(this.config.socketFactory=function(){return new t},c=[new s(this.config)]);this.config.strategies=c;this.connection=new m(a);this.connection.on("state",this._onConnectionState.bind(this));this.connection.on("message",this._onMessage.bind(this))},connect:function(a){return new this.Promise(function(c){var b=function(){c.resolve();a&&a(null,this)};
if(this.connection.state===this.connection.AUTHENTICATED)b();else{var d=function(a,c){a===this.connection.AUTHENTICATED&&(this.connection.off("state",d),b())}.bind(this);this.connection.on("state",d);this.connection.state!==this.connection.WAITING&&this.connection.state!==this.connection.CLOSED||this.connection.connect()}}.bind(this))},subscribeState:function(a,c,b){var d=function(){this._subscribeQueue(a,function(a){return a.getStateMount(c)},b)}.bind(this);this.connection.state!==this.connection.AUTHENTICATED?
this.__queuedSubscriptions.push(d):d()},subscribeMessage:function(a,c,b){var d=function(){this._subscribeQueue(a,function(a){return a.getMessageMount(c)},b)}.bind(this);this.connection.state!==this.connection.AUTHENTICATED?this.__queuedSubscriptions.push(d):d()},close:function(){this.connection.close();_(this.queues).each(function(a){_(a.messageMounts).each(function(a){a.off()});a.messageMounts=[];_(a.stateMounts).each(function(a){a.off()});a.stateMounts=[]});this.queues=[]},sendMessage:function(a,
c,b,d){this._send("msg_c2g_send_message",{queueName:a,mountName:c,message:b},d)},sendStateChange:function(a,c,b,d){this._send("msg_c2g_state_change",{queueName:a,mountName:c,delta:b},d)},_onConnectionState:function(a,c){var b={status:"undefined"!==typeof l[a]?l[a]:"unknown"};"undefined"!==typeof c&&(b.connectAt=c);this.state.set(b);a===this.connection.AUTHENTICATED&&(_.each(this.queues,function(a){this._send("msg_c2g_subscribe",[a.name])}.bind(this)),_.each(this.__queuedSubscriptions,function(a){a()}.bind(this)),
this.__queuedSubscriptions=[])},_subscribeQueue:function(a,c,b){"undefined"===typeof this.queues[a]&&this._send("msg_c2g_subscribe",[a]);b(null,c(this._getOrCreateQueue(a)))},_unsubscribeQueue:function(a,c){this._send("msg_c2g_unsubscribe",[a],u(c,function(){"undefined"!==typeof this.queues[a]&&delete this.queues[a]}.bind(this)))},_onMessage:function(a){var c="_on_"+a.type;if("undefined"===typeof this[c])this._onUnhandledMessage(a);else this[c](a.data)},_send:function(a,c,b){"undefined"===typeof b&&
(b=function(){});this.connection.state===this.connection.AUTHENTICATED?(this.connection.send(a,c),b(null)):b("Cannot send data: Not authenticated!")},_getOrCreateQueue:function(a){"undefined"===typeof this.queues[a]&&(this.queues[a]=new x(this,a));return this.queues[a]},_on_msg_g2c_result:function(a){this._receiveOpId(a.opId,a.error)},_on_msg_g2c_left_queue:function(a){"undefined"!==typeof this.queues[a.queueName]&&this.queues[a.queueName].dispatchSubscriberUpdate({userId:a.userId,action:"left"})},
_on_msg_g2c_joined_queue:function(a){this._getOrCreateQueue(a.queueName);this.queues[a.queueName].dispatchSubscriberUpdate({userId:a.userId,action:"joined"})},_on_msg_g2c_create_mount:function(a){switch(a.type){case "message":this._getOrCreateQueue(a.queueName).initMessageMount(a.mountName);break;case "state":this._getOrCreateQueue(a.queueName).initStateMount(a.mountName,a.state)}},_on_msg_g2c_send_message:function(a){"undefined"!==typeof this.queues[a.queueName]&&this.queues[a.queueName].dispatchMessage(a.mountName,
{userId:a.userId,message:a.message})},_on_msg_g2c_state_change:function(a){"undefined"!==typeof this.queues[a.queueName]&&this.queues[a.queueName].dispatchState(a.mountName,{userId:a.userId,delta:a.delta})},_onUnhandledMessage:function(a){console.warn("Unhandled IMQ message",a)}});_.extend(f.prototype,Backbone.Events);var t=IMVU.BaseClass.extend("NoOpSocket",{initialize:function(){this.readyState=this.CLOSED},CLOSED:4,addEventListener:function(){},removeEventListener:function(){},close:function(){},
send:function(){}});return{ImqManager:f,ImqMessageMount:p,ImqStateMount:q,NoOpSocket:t}});
